using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyCompanyAttribute("James Hicks")]
[assembly: AssemblyVersionAttribute("1.0.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: AssemblyInformationalVersionAttribute("1.0.0.")]
[assembly: AssemblyTitleAttribute("Db4oFramework")]
[assembly: AssemblyProductAttribute("Db4oFramework")]
[assembly: AssemblyDescriptionAttribute("Db4oFramework is a product of James Hicks - git://github.com/jhicks/Db4oFramework" +
    ".git.")]
[assembly: AssemblyTrademarkAttribute("Db4oFramework - James Hicks")]
[assembly: AssemblyCopyrightAttribute("Copyright 2010 James Hicks, - Original author or authors")]

